#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="${RISCV_TESTS_DIR:-$ROOT/_build/riscv-tests-src}"
MANIFEST_FILE="$ROOT/tools/riscv-tests-manifest.tsv"
GEN_FILE="$ROOT/riscv_tests_official_generated.mbt"

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required tool: $1" >&2
    exit 1
  fi
}

require_tool awk
require_tool od

emit_bytes() {
  local path="$1"
  od -An -v -t u1 "$path" | awk '
    BEGIN { printf("Bytes::from_array([") }
    {
      for (i = 1; i <= NF; i++) {
        if (count > 0) {
          printf(", ")
        }
        if (count > 0 && count % 16 == 0) {
          printf("\n        ")
        }
        printf("%s", $i)
        count++
      }
    }
    END { printf("])") }
  '
}

tmp_file="$(mktemp)"

{
  echo "///|"
  echo "// Generated by scripts/update-riscv-tests-official-generated.sh. Do not edit by hand."
  echo "pub struct OfficialRiscvTestBinary {"
  echo "  suite : String"
  echo "  name : String"
  echo "  arch : String"
  echo "  tier : String"
  echo "  elf : Bytes"
  echo "  max_steps : Int"
  echo "}"
  echo
  echo "///|"
  echo "pub fn all_official_riscv_tests() -> Array[OfficialRiscvTestBinary] {"
  echo "  ["
} >"$tmp_file"

while IFS=$'\t' read -r suite test_name arch tier; do
  if [[ -z "${suite}" || "${suite}" == \#* ]]; then
    continue
  fi

  elf_path="$SRC_DIR/isa/${suite}-p-${test_name}"
  if [[ ! -f "$elf_path" ]]; then
    echo "missing official test ELF: $elf_path" >&2
    echo "run ./scripts/build-riscv-tests-official.sh first" >&2
    exit 1
  fi

  {
    echo "    {"
    echo "      suite: \"$suite\","
    echo "      name: \"$test_name\","
    echo "      arch: \"$arch\","
    echo "      tier: \"$tier\","
    printf "      elf: "
    emit_bytes "$elf_path"
    echo ","
    echo "      max_steps: 200000,"
    echo "    },"
  } >>"$tmp_file"
done <"$MANIFEST_FILE"

{
  echo "  ]"
  echo "}"
  echo
  echo "///|"
  echo "pub fn gating_official_riscv_tests() -> Array[OfficialRiscvTestBinary] {"
  echo "  all_official_riscv_tests().filter(fn(test_case) { test_case.tier == \"gating\" })"
  echo "}"
  echo
  echo "///|"
  echo "pub fn survey_official_riscv_tests() -> Array[OfficialRiscvTestBinary] {"
  echo "  all_official_riscv_tests().filter(fn(test_case) { test_case.tier == \"survey\" })"
  echo "}"
} >>"$tmp_file"

mv "$tmp_file" "$GEN_FILE"
echo "updated $GEN_FILE"
